// Generated from quotes-review/candidates.json. Do not hand-edit; edit the
// review data and re-run the generator so provenance stays intact.
//
// Quote text is from Wikiquote (CC BY-SA) except where provenance is
// 'owner-confirmed' — those were supplied and confirmed by the site owner.

export interface Quote {
  /** The line itself, verbatim. Never paraphrase. */
  q: string;
  /** Speaker, duo, or show-level credit. Not always a single character. */
  who: string;
  show: string;
  /** Lexical retrieval keys, matched against the user's message. */
  tags: string[];
  /** Season.episode, when the source records one. */
  episode?: string;
  episodeName?: string;
  source?: string;
  provenance: 'wikiquote' | 'wikiquote-verified' | 'owner-confirmed';
  /** Preceding line, when the quote is a punchline that needs one. */
  setup?: string;
  /** Set for dictionary-style entries rather than spoken lines. */
  kind?: 'definition';
  definition?: string;
}

export const QUOTES: Quote[] = [
  { q: 'I\'d never thought I\'d miss a hand so much.', who: 'Buster Bluth', show: 'Arrested Development', tags: ['time', 'confusion', 'understanding', 'miss', 'hand'], episode: '2.3', episodeName: 'Amigos', source: 'https://en.wikiquote.org/wiki/Arrested_Development', provenance: 'wikiquote' },
  { q: 'I am no longer a Mother-boy, I am a Mother-man!', who: 'Buster Bluth', show: 'Arrested Development', tags: ['mother'], episode: '4.14', episodeName: 'Off the Hook', source: 'https://en.wikiquote.org/wiki/Arrested_Development', provenance: 'wikiquote' },
  { q: 'I\'m a monster!', who: 'Buster Bluth', show: 'Arrested Development', tags: ['shame', 'self-loathing', 'panic', 'monster'], provenance: 'owner-confirmed' },
  { q: 'I\'ve made a huge mistake.', who: 'GOB Bluth', show: 'Arrested Development', tags: ['mistake', 'regret', 'error', 'oops', 'failure', 'huge'], provenance: 'owner-confirmed' },
  { q: 'Illusion, Michael. A trick is something a whore does for money.', who: 'GOB Bluth', show: 'Arrested Development', tags: ['magic', 'correction', 'pedantic', 'money', 'finance', 'illusion', 'trick', 'whore'], episode: '1.1', episodeName: 'Pilot', source: 'https://en.wikiquote.org/wiki/Arrested_Development', provenance: 'wikiquote-verified' },
  { q: 'There\'s always money in the banana stand.', who: 'George Bluth Sr.', show: 'Arrested Development', tags: ['money', 'finance', 'time', 'there\'s', 'banana', 'stand'], episode: '1.2', episodeName: 'Top Banana', source: 'https://en.wikiquote.org/wiki/Arrested_Development', provenance: 'wikiquote' },
  { q: 'I don\'t understand the question, and I won\'t respond to it.', who: 'Lucille Bluth', show: 'Arrested Development', tags: ['confusion', 'understanding', 'understand', 'question', 'respond'], episode: '1.11', episodeName: 'Public Relations', source: 'https://en.wikiquote.org/wiki/Arrested_Development', provenance: 'wikiquote' },
  { q: 'I don\'t have the milk of mother\'s kindness in me anymore.', who: 'Lucille Bluth', show: 'Arrested Development', tags: ['milk', 'mother\'s', 'kindness', 'anymore'], episode: '1.14', episodeName: 'Shock and Aww', source: 'https://en.wikiquote.org/wiki/Arrested_Development', provenance: 'wikiquote' },
  { q: 'I want to cry so bad, but I don\'t think I can spare the moisture.', who: 'Lucille Bluth', show: 'Arrested Development', tags: ['sad', 'crying', 'emotion', 'spare', 'moisture'], episode: '3.7', episodeName: 'Prison Break-In', source: 'https://en.wikiquote.org/wiki/Arrested_Development', provenance: 'wikiquote' },
  { q: 'You are a worse psychiatrist than you are a son-in-law, and you will never get work as an actor because you have no talent.', who: 'Lucille Bluth', show: 'Arrested Development', tags: ['work', 'job', 'career', 'time', 'crime', 'law', 'worse', 'psychiatrist', 'actor'], episode: '2.11', episodeName: 'Out on a Limb', source: 'https://en.wikiquote.org/wiki/Arrested_Development', provenance: 'wikiquote' },
  { q: 'I\'m a saint, you know. I\'m a living saint, and I get absolutely nothing out of it.', who: 'Michael Bluth', show: 'Arrested Development', tags: ['philosophy', 'morality', 'confusion', 'understanding', 'saint', 'living', 'absolutely'], episode: '1.9', episodeName: 'Storming the Castle', source: 'https://en.wikiquote.org/wiki/Arrested_Development', provenance: 'wikiquote' },
  { q: 'Her?', who: 'Michael Bluth', show: 'Arrested Development', tags: ['disgust', 'surprise', 'recoil'], provenance: 'owner-confirmed' },
  { q: 'I don\'t know what I expected.', who: 'Michael Bluth', show: 'Arrested Development', tags: ['resignation', 'regret', 'consequence', 'confusion', 'understanding', 'expected'], provenance: 'owner-confirmed' },
  { q: 'Steve Holt!', who: 'Steve Holt', show: 'Arrested Development', tags: ['triumph', 'celebrate', 'name', 'steve', 'holt'], episode: '1.3', episodeName: 'Bringing Up Buster', source: 'https://en.wikiquote.org/wiki/Arrested_Development', provenance: 'wikiquote-verified' },
  { q: 'I just blue myself.', who: 'Tobias Fünke', show: 'Arrested Development', tags: ['innuendo', 'accident', 'self', 'blue'], episode: '2.1', episodeName: 'The One Where Michael Leaves', source: 'https://en.wikiquote.org/wiki/Arrested_Development', provenance: 'wikiquote-verified' },
  { q: 'For as long as I can remember, I always wanted to be in a mafia movie.', who: 'Abed Nadir', show: 'Community', tags: ['time', 'television', 'film', 'media', 'long', 'remember', 'mafia', 'movie'], episode: '1.21', episodeName: 'Contemporary American Poultry', source: 'https://en.wikiquote.org/wiki/Community/Season_1', provenance: 'wikiquote' },
  { q: 'Blind date. I\'ve always thought of myself as more of an acquired taste, but okay.', who: 'Abed Nadir', show: 'Community', tags: ['time', 'confusion', 'understanding', 'blind', 'date', 'acquired'], episode: '4.08', episodeName: 'Herstory of Dance', source: 'https://en.wikiquote.org/wiki/Community/Season_4', provenance: 'wikiquote' },
  { q: 'I can tell life from TV, Jeff. TV makes sense: it has structure, logic, rules and likable leading men. In life, we have this...we have you.', who: 'Abed Nadir', show: 'Community', tags: ['television', 'film', 'media', 'life', 'makes', 'sense', 'structure'], episode: '2.01', episodeName: 'Anthropology 101', source: 'https://en.wikiquote.org/wiki/Community/Season_2', provenance: 'wikiquote' },
  { q: 'Speaking of days, I never got a chance to wish you a happy birthday. Or Halloween, or Christmas, or any other specific calendar event.', who: 'Abed Nadir', show: 'Community', tags: ['luck', 'risk', 'chance', 'time', 'celebration', 'holiday', 'speaking', 'days', 'wish'], episode: '5.13', episodeName: 'Basic Sandwich', source: 'https://en.wikiquote.org/wiki/Community/Season_5', provenance: 'wikiquote' },
  { q: 'Cool. Cool cool cool.', who: 'Abed Nadir', show: 'Community', tags: ['agreement', 'awkward', 'catchphrase', 'cool'], provenance: 'owner-confirmed' },
  { q: 'Six seasons and a movie!', who: 'Abed Nadir', show: 'Community', tags: ['optimism', 'television', 'rallying', 'film', 'media', 'seasons', 'movie'], episode: '2.21', episodeName: 'Paradigms of Human Memory', source: 'https://en.wikiquote.org/wiki/Community/Season_2', provenance: 'wikiquote-verified' },
  { q: 'I must\'ve missed that.', who: 'Abed Nadir', show: 'Community', tags: ['deadpan', 'film', 'oblivious', 'must\'ve', 'missed'], provenance: 'owner-confirmed', setup: 'Kickpuncher narrator: "It is the year 2006 A.D. and nuclear war has ravaged the planet."' },
  { q: 'Shut up, Leonard! I once mistook six people for you at a pharmacy!', who: 'Britta Perry', show: 'Community', tags: ['shut', 'leonard', 'mistook', 'pharmacy'], episode: '6.01', episodeName: 'Ladders', source: 'https://en.wikiquote.org/wiki/Community/Season_6', provenance: 'wikiquote' },
  { q: 'Am I the only person enraged by the fact that corporations are taking human form? I totally predicted this in my high school newspaper column: Britta Unfiltered.', who: 'Britta Perry', show: 'Community', tags: ['enraged', 'fact', 'corporations', 'taking', 'human'], episode: '3.13', episodeName: 'Digital Exploration of Interior Design', source: 'https://en.wikiquote.org/wiki/Community/Season_3', provenance: 'wikiquote' },
  { q: 'I am hereby banning change from this campus.', who: 'Dean Pelton', show: 'Community', tags: ['hereby', 'banning', 'change', 'campus'], episode: '5.03', episodeName: 'Basic Intergluteal Numismatics', source: 'https://en.wikiquote.org/wiki/Community/Season_5', provenance: 'wikiquote' },
  { q: 'I don\'t want to sound like a defeatist, but...we\'re defeated.', who: 'Jeff Winger', show: 'Community', tags: ['sound', 'defeatist', 'defeated'], episode: '1.24', episodeName: 'English as a Second Language', source: 'https://en.wikiquote.org/wiki/Community/Season_1', provenance: 'wikiquote' },
  { q: 'I\'m no sociopath. I always know what I\'m doing is wrong.', who: 'Jeff Winger', show: 'Community', tags: ['mistake', 'failure', 'regret', 'time', 'confusion', 'understanding', 'sociopath', 'wrong'], episode: '3.05', episodeName: 'Horror Fiction in Seven Spooky Steps', source: 'https://en.wikiquote.org/wiki/Community/Season_3', provenance: 'wikiquote' },
  { q: 'I\'ve become a stranger to myself. I\'m bald now. I\'ve always been bald. I merely dreamt of having hair, and now, the bald man is awake.', who: 'Jeff Winger', show: 'Community', tags: ['time', 'become', 'stranger', 'bald', 'merely'], episode: '3.08', episodeName: 'Documentary Filmmaking: Redux', source: 'https://en.wikiquote.org/wiki/Community/Season_3', provenance: 'wikiquote' },
  { q: 'My latest theory? Maybe I\'m a god. I\'ve denied the signs for too long.', who: 'Jeff Winger', show: 'Community', tags: ['philosophy', 'morality', 'latest', 'theory', 'denied', 'signs', 'long'], episode: '2.09', episodeName: 'Conspiracy Theories and Interior Design', source: 'https://en.wikiquote.org/wiki/Community/Season_2', provenance: 'wikiquote' },
  { q: 'I\'m not an idealist; I\'m a pragmatist. And it\'s never pragmatic to piss you guys off, so... Fine.', who: 'Jeff Winger', show: 'Community', tags: ['time', 'idealist', 'pragmatist', 'pragmatic', 'piss'], episode: '6.06', episodeName: 'Basic Email Security', source: 'https://en.wikiquote.org/wiki/Community/Season_6', provenance: 'wikiquote' },
  { q: 'I see your value now.', who: 'Jeff Winger', show: 'Community', tags: ['recognition', 'respect', 'grudging', 'value'], episode: '1.01', episodeName: 'Pilot', source: 'https://en.wikiquote.org/wiki/Community/Season_1', provenance: 'wikiquote-verified' },
  { q: 'Pop pop!', who: 'Magnitude', show: 'Community', tags: ['catchphrase', 'celebrate', 'party'], provenance: 'owner-confirmed' },
  { q: 'If you\'re not, I\'m sorry. If you are, I\'m a hero. It\'s a risk I\'m prepared to take.', who: 'Pierce Hawthorne', show: 'Community', tags: ['luck', 'risk', 'chance', 'sorry', 'hero', 'prepared'], episode: '1.22', episodeName: 'The Art of Discourse', source: 'https://en.wikiquote.org/wiki/Community/Season_1', provenance: 'wikiquote' },
  { q: 'I don\'t know. I looked it up on the Wikipedia.', who: 'Pierce Hawthorne', show: 'Community', tags: ['technology', 'internet', 'confusion', 'understanding', 'wikipedia'], episode: '3.06', episodeName: 'Advanced Gay', source: 'https://en.wikiquote.org/wiki/Community/Season_3', provenance: 'wikiquote' },
  { q: 'Streets ahead.', who: 'Pierce Hawthorne', show: 'Community', tags: ['slang', 'superiority', 'invented', 'streets', 'ahead'], source: 'https://en.wikiquote.org/wiki/Community/Season_1', provenance: 'wikiquote-verified' },
  { q: 'Will it get me through this movie?', who: 'Shirley Bennett', show: 'Community', tags: ['endurance', 'boredom', 'film', 'television', 'media', 'movie'], provenance: 'owner-confirmed', setup: 'A drug dealer offers Shirley "mega-dope" during Kickpuncher' },
  { q: 'The question isn\'t where, constable, but when.', who: 'The Inspector', show: 'Community', tags: ['time', 'mystery', 'parody', 'question', 'constable'], provenance: 'owner-confirmed' },
  { q: 'I don\'t know why, but I\'m kind of over zombies.', who: 'Troy Barnes', show: 'Community', tags: ['confusion', 'understanding', 'kind', 'zombies'], episode: '2.06', episodeName: 'Epidemiology', source: 'https://en.wikiquote.org/wiki/Community/Season_2', provenance: 'wikiquote' },
  { q: 'Alcohol makes people sad. It\'s the Lifetime movie of beverages.', who: 'Troy Barnes', show: 'Community', tags: ['sad', 'crying', 'emotion', 'drinking', 'alcohol', 'television', 'film', 'media', 'makes'], episode: '2.10', episodeName: 'Mixology Certification', source: 'https://en.wikiquote.org/wiki/Community/Season_2', provenance: 'wikiquote' },
  { q: 'Sounds like a Thanksgiving at my house.', who: 'Troy Barnes', show: 'Community', tags: ['family', 'chaos', 'holiday', 'deadpan', 'celebration', 'sounds', 'thanksgiving', 'house'], provenance: 'owner-confirmed', setup: 'Kickpuncher narrator: "Detroit is a firezone ruled by scavengers, drug dealers, and terrorists."' },
  { q: 'Troy and Abed in the morning!', who: 'Troy Barnes and Abed Nadir', show: 'Community', tags: ['duo', 'announcement', 'friendship', 'time', 'morning'], provenance: 'owner-confirmed' },
  { q: 'Britta\'d', who: 'the study group', show: 'Community', tags: ['mistake', 'failure', 'verb', 'definition', 'regret', 'britta\'d', 'completely', 'worst'], provenance: 'owner-confirmed', kind: 'definition', definition: 'to make a mistake so completely as to be the worst' },
  { q: 'When life gives you lemons, make lemonade. I read that one on a can of lemonade. I like to think it applies to life.', who: 'Andy Dwyer', show: 'Parks and Recreation', tags: ['books', 'reading', 'life', 'gives', 'lemons', 'lemonade', 'read'], episode: '3.15', episodeName: 'The Bubble', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_3%29', provenance: 'wikiquote' },
  { q: 'I\'m never gonna be a cop. I\'m gonna have to be a robber.', who: 'Andy Dwyer', show: 'Parks and Recreation', tags: ['time', 'crime', 'law', 'robber'], episode: '5.2', episodeName: 'Soda Tax', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_5%29', provenance: 'wikiquote' },
  { q: 'I can never tell if people are lying to me. I hope that doesn\'t come up in my police work', who: 'Andy Dwyer', show: 'Parks and Recreation', tags: ['work', 'job', 'career', 'honesty', 'lying', 'secrets', 'time', 'crime', 'law'], episode: '5.7', episodeName: 'Leslie vs. April', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_5%29', provenance: 'wikiquote' },
  { q: 'I AM NOT CRYING, OK?! I\'M ALLERGIC TO JERKS!', who: 'Andy Dwyer', show: 'Parks and Recreation', tags: ['sad', 'crying', 'emotion', 'allergic', 'jerks'], episode: '2.7', episodeName: 'Greg Pikitis', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_2%29', provenance: 'wikiquote' },
  { q: 'I wish I could help you bro, I don\'t know if I can. You\'re like the second smartest guy I know. You should go to the first smartest guy I know.', who: 'Andy Dwyer', show: 'Parks and Recreation', tags: ['help', 'advice', 'confusion', 'understanding', 'wish', 'smartest'], episode: '4.14', episodeName: 'Operation Ann', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_4%29', provenance: 'wikiquote' },
  { q: 'I am not good at keeping secrets! That\'s exactly what I told Kyle when he told me his wife was cheating on him.', who: 'Andy Dwyer', show: 'Parks and Recreation', tags: ['good', 'keeping', 'secrets', 'exactly', 'kyle'], episode: '6.20', episodeName: 'One in 8,000', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_6%29', provenance: 'wikiquote' },
  { q: 'I swear on this dead crow that I will never cook for you.', who: 'April Ludgate', show: 'Parks and Recreation', tags: ['death', 'mortality', 'dark', 'time', 'animals', 'swear', 'dead', 'crow', 'cook'], episode: '3.10', episodeName: 'Soulmates', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_3%29', provenance: 'wikiquote' },
  { q: 'I don\'t like lotion. I like my hands to be cracked and calloused like a railway worker.', who: 'April Ludgate', show: 'Parks and Recreation', tags: ['lotion', 'hands', 'cracked', 'calloused', 'railway', 'worker'], episode: '5.18', episodeName: 'Animal Control', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_5%29', provenance: 'wikiquote' },
  { q: 'I would love it if you ran an insane campaign and basically turned into the Joker...but that means you probably shouldn\'t do it.', who: 'April Ludgate', show: 'Parks and Recreation', tags: ['love', 'affection', 'romance', 'politics', 'government', 'insane', 'campaign', 'joker'], episode: '6.10', episodeName: 'Second Chunce', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_6%29', provenance: 'wikiquote' },
  { q: 'She\'s the worst person I\'ve ever met. I want to travel the world with her.', who: 'April Ludgate', show: 'Parks and Recreation', tags: ['mistake', 'failure', 'regret', 'she\'s', 'worst', 'ever', 'travel', 'world'], episode: '6.4', episodeName: 'Doppelgängers', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_6%29', provenance: 'wikiquote' },
  { q: 'Everybody says they care about the issues, but at the end of the day all anyone really wants is free clothing shot at them from a cannon.', who: 'Ben Wyatt', show: 'Parks and Recreation', tags: ['time', 'care', 'issues', 'anyone', 'wants', 'free'], episode: '4.21', episodeName: 'Bus Tour', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_4%29', provenance: 'wikiquote' },
  { q: 'If I had to have anybody tell me that I have cancer, I would want it to be me.', who: 'Chris Traeger', show: 'Parks and Recreation', tags: ['illness', 'pain', 'health', 'cancer'], episode: '4.20', episodeName: 'The Debate', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_4%29', provenance: 'wikiquote' },
  { q: 'This is the best possible job for me. I could literally make anything sound positive.', who: 'Chris Traeger', show: 'Parks and Recreation', tags: ['work', 'job', 'career', 'praise', 'compliment', 'best', 'possible'], episode: '4.20', episodeName: 'The Debate', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_4%29', provenance: 'wikiquote' },
  { q: 'Literally.', who: 'Chris Traeger', show: 'Parks and Recreation', tags: ['emphasis', 'agreement', 'catchphrase'], provenance: 'owner-confirmed' },
  { q: 'Everything hurts and I\'m dying.', who: 'Chris Traeger', show: 'Parks and Recreation', tags: ['pain', 'illness', 'exhaustion', 'complaint', 'death', 'mortality', 'dark', 'hurts', 'dying'], source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_4%29', provenance: 'wikiquote-verified' },
  { q: 'Stop...POOPING.', who: 'Chris Traeger', show: 'Parks and Recreation', tags: ['illness', 'delirium', 'absurd', 'stop', 'pooping'], episode: '3.2', episodeName: 'Flu Season', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_3%29', provenance: 'wikiquote-verified' },
  { q: 'Do I look like I\'m joking? Dating is a zero sum game. If you get a man, I don\'t get that man.', who: 'Donna Meagle', show: 'Parks and Recreation', tags: ['technology', 'internet', 'joking', 'dating', 'zero', 'game'], episode: '3.9', episodeName: 'Andy and April\'s Fancy Party', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_3%29', provenance: 'wikiquote' },
  { q: 'The library is the worst group of people ever assembled in history. They\'re mean, conniving, rude and extremely well read which makes them very dangerous.', who: 'Leslie Knope', show: 'Parks and Recreation', tags: ['mistake', 'failure', 'regret', 'books', 'reading', 'library', 'worst', 'group', 'ever'], episode: '2.8', episodeName: 'Ron and Tammy', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_2%29', provenance: 'wikiquote' },
  { q: 'Ann, you beautiful tropical fish.', who: 'Leslie Knope', show: 'Parks and Recreation', tags: ['compliment', 'friendship', 'affection', 'praise', 'outdoors', 'hobbies', 'beautiful', 'tropical', 'fish'], episode: '4.11', episodeName: 'The Comeback Kid', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_4%29', provenance: 'wikiquote-verified' },
  { q: 'I love you and I like you.', who: 'Leslie Knope and Ben Wyatt', show: 'Parks and Recreation', tags: ['love', 'affection', 'sincere', 'romance'], provenance: 'owner-confirmed' },
  { q: 'You\'re 5,000 candles in the wind.', who: 'Mouse Rat', show: 'Parks and Recreation', tags: ['tribute', 'grief', 'song', 'memorial', 'candles', 'wind'], provenance: 'owner-confirmed' },
  { q: 'It\'s a hamburger, made out of meat, on a bun, with nothing. Add ketchup if you want, I couldn\'t care less.', who: 'Ron Swanson', show: 'Parks and Recreation', tags: ['food', 'hunger', 'eating', 'hamburger', 'meat', 'ketchup'], episode: '3.10', episodeName: 'Soulmates', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_3%29', provenance: 'wikiquote' },
  { q: 'There\'s a hot, spinning cone of meat in that Greek restaurant next door. I don\'t know what it is, but I\'d like to eat the whole thing.', who: 'Ron Swanson', show: 'Parks and Recreation', tags: ['food', 'hunger', 'eating', 'confusion', 'understanding', 'there\'s', 'spinning', 'cone', 'meat', 'greek'], episode: '4.19', episodeName: 'Live Ammo', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_4%29', provenance: 'wikiquote' },
  { q: 'Hmm. If there were more food and fewer people this would be the perfect party.', who: 'Ron Swanson', show: 'Parks and Recreation', tags: ['food', 'hunger', 'eating', 'celebration', 'holiday', 'fewer', 'perfect', 'party'], episode: '5.8', episodeName: 'Pawnee Commons', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_5%29', provenance: 'wikiquote' },
  { q: 'How\'s that zero dollar bid coming along? You know in my experience with capitalism, people normally expect money in exchange for their goods and land.', who: 'Ron Swanson', show: 'Parks and Recreation', tags: ['money', 'finance', 'confusion', 'understanding', 'how\'s', 'zero', 'dollar', 'coming', 'along', 'experience'], episode: '7.2', episodeName: 'Ron & Jammy', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_7%29', provenance: 'wikiquote' },
  { q: 'Who\'s to say what works. You know, you find somebody you like and you roll the dice. It\'s all anybody can do.', who: 'Ron Swanson', show: 'Parks and Recreation', tags: ['luck', 'risk', 'chance', 'confusion', 'understanding', 'who\'s', 'works', 'find', 'roll'], episode: '3.9', episodeName: 'Andy and April\'s Fancy Party', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_3%29', provenance: 'wikiquote' },
  { q: 'There is no street parking at my house. My house is not even on a street.', who: 'Ron Swanson', show: 'Parks and Recreation', tags: ['street', 'parking', 'house', 'even'], episode: '3.12', episodeName: 'Eagleton', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_3%29', provenance: 'wikiquote' },
  { q: 'I have cried twice in my life. Once, when I was 7 and was hit by a bus, and again when I learned that L\'il Sebastian had passed.', who: 'Ron Swanson', show: 'Parks and Recreation', tags: ['sad', 'crying', 'emotion', 'cried', 'twice', 'life', 'learned', 'l\'il', 'sebastian'], episode: '3.16', episodeName: 'Li\'l Sebastian', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_3%29', provenance: 'wikiquote' },
  { q: 'Never half-ass two things. Whole-ass one thing.', who: 'Ron Swanson', show: 'Parks and Recreation', tags: ['time', 'half'], episode: '4.16', episodeName: 'Sweet Sixteen', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_4%29', provenance: 'wikiquote' },
  { q: 'Just give me all the bacon and eggs you have. Wait, wait. I\'m worried what you just heard was, "Give me a lot of bacon and eggs." What I said was, "Give me all the bacon and eggs you have". Do you understand?', who: 'Ron Swanson', show: 'Parks and Recreation', tags: ['food', 'breakfast', 'excess', 'clarity', 'hunger', 'eating', 'confusion', 'understanding', 'bacon'], episode: '3.6', episodeName: 'Indianapolis', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_3%29', provenance: 'wikiquote-verified' },
  { q: 'There\'s only one thing I hate more than lying: skim milk. Which is water that\'s lying about being milk.', who: 'Ron Swanson', show: 'Parks and Recreation', tags: ['lying', 'fake', 'milk', 'contempt', 'honesty', 'secrets', 'anger', 'there\'s', 'hate'], episode: '5.17', episodeName: 'Partridge', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_5%29', provenance: 'wikiquote-verified' },
  { q: 'Crying: acceptable at funerals and the Grand Canyon.', who: 'Ron Swanson', show: 'Parks and Recreation', tags: ['crying', 'emotion', 'stoic', 'rules', 'sad', 'acceptable', 'funerals', 'grand', 'canyon'], episode: '3.1', episodeName: 'Go Big or Go Home', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_3%29', provenance: 'wikiquote-verified' },
  { q: 'I\'d wish you the best of luck, but I believe luck is a concept created by the weak to explain their failures.', who: 'Ron Swanson', show: 'Parks and Recreation', tags: ['luck', 'encouragement', 'contempt', 'failure', 'risk', 'chance', 'praise', 'compliment', 'wish', 'best'], provenance: 'owner-confirmed' },
  { q: 'Velvet slippys, cashmere socks, velvet pants, cashmere turtle. I\'m a cashmere, velvet candy cane.', who: 'Tom Haverford', show: 'Parks and Recreation', tags: ['food', 'hunger', 'eating', 'velvet', 'slippys', 'cashmere', 'socks', 'pants', 'turtle'], episode: '4.4', episodeName: 'Pawnee Rangers', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_4%29', provenance: 'wikiquote' },
  { q: 'I have never taken the high road. But I tell other people to \'cause then there\'s more room for me on the low road.', who: 'Tom Haverford', show: 'Parks and Recreation', tags: ['time', 'taken', 'high', 'road'], episode: '2.8', episodeName: 'Ron and Tammy', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_2%29', provenance: 'wikiquote' },
  { q: 'When you\'re in government, there\'s a million ways to exploit your power. Have I ever given into that temptation? No. Never. I\'m not that kind of politician.', who: 'Tom Haverford', show: 'Parks and Recreation', tags: ['time', 'politics', 'government', 'there\'s', 'million', 'ways', 'exploit', 'power'], episode: '1.4', episodeName: 'Boys\' Club', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_1%29', provenance: 'wikiquote' },
  { q: 'Treat yo self.', who: 'Tom Haverford and Donna Meagle', show: 'Parks and Recreation', tags: ['indulgence', 'money', 'celebrate', 'self-care', 'treat', 'self'], episode: '4.4', episodeName: 'Pawnee Rangers', source: 'https://en.wikiquote.org/wiki/Parks_and_Recreation_%28season_4%29', provenance: 'wikiquote-verified' },
  { q: 'Welcome to the Medium Place.', who: 'Beattie', show: 'The Good Place', tags: ['afterlife', 'mediocre', 'introduction', 'welcome', 'medium', 'place'], episode: '1.12', episodeName: 'Chapter 12 – Mindy St. Claire', source: 'https://en.wikiquote.org/wiki/The_Good_Place', provenance: 'wikiquote-verified' },
  { q: 'I am in paradise! I should be doing paradise things, like rowing out on a lake with a good bottle of wine, reading French poetry.', who: 'Chidi Anagonye', show: 'The Good Place', tags: ['drinking', 'alcohol', 'books', 'reading', 'paradise', 'rowing', 'lake', 'good'], episode: '1.5', episodeName: 'Chapter 5 – Category 55 Emergency Doomsday Crisis', source: 'https://en.wikiquote.org/wiki/The_Good_Place', provenance: 'wikiquote' },
  { q: 'Before I can teach Michael to be good, I have to force him to think about what we used to think about: that life has an end, and therefore our actions have meaning.', who: 'Chidi Anagonye', show: 'The Good Place', tags: ['teach', 'good', 'force'], episode: '2.5', episodeName: 'Chapter 18 – Existential Crisis', source: 'https://en.wikiquote.org/wiki/The_Good_Place', provenance: 'wikiquote' },
  { q: 'I don\'t know what to do here. This is a mess, morally speaking. This is a putrid, disgusting bowl of ethical soup.', who: 'Chidi Anagonye', show: 'The Good Place', tags: ['confusion', 'understanding', 'mess', 'morally', 'speaking', 'putrid', 'disgusting', 'bowl'], episode: '1.2', episodeName: 'Chapter 2 – Flying', source: 'https://en.wikiquote.org/wiki/The_Good_Place', provenance: 'wikiquote' },
  { q: 'You just casually cited Immanuel Kant. I know we\'re in a miserable bind here, but this might be the proudest day of my life.', who: 'Chidi Anagonye', show: 'The Good Place', tags: ['time', 'philosophy', 'morality', 'confusion', 'understanding', 'casually', 'cited', 'immanuel', 'kant', 'miserable'], episode: '1.8', episodeName: 'Chapter 8 – Most Improved Player', source: 'https://en.wikiquote.org/wiki/The_Good_Place', provenance: 'wikiquote' },
  { q: 'The wave was just a different way for the water to be, for a little while.', who: 'Chidi Anagonye', show: 'The Good Place', tags: ['death', 'grief', 'comfort', 'buddhism', 'philosophy', 'wave', 'different', 'water'], provenance: 'owner-confirmed', setup: 'From the finale wave-and-ocean speech about death' },
  { q: 'As my mom always used to say, if a cop handcuffs you to a bike rack, there\'s always something you can gnaw through.', who: 'Eleanor Shellstrop', show: 'The Good Place', tags: ['time', 'crime', 'law', 'used', 'handcuffs', 'bike', 'rack', 'there\'s'], episode: '2.3', episodeName: 'Chapter 16 – Dance Dance Resolution', source: 'https://en.wikiquote.org/wiki/The_Good_Place', provenance: 'wikiquote' },
  { q: 'You what I just realized? I always say that whenever I leave a room. But now? It\'s accurate! I will LITERALLY... SEE ALL OF YOU IN HELL.', who: 'Eleanor Shellstrop', show: 'The Good Place', tags: ['time', 'philosophy', 'morality', 'realized', 'whenever', 'leave', 'room', 'accurate'], episode: '3.4', episodeName: 'Chapter 31 – Jeremy Bearimy', source: 'https://en.wikiquote.org/wiki/The_Good_Place', provenance: 'wikiquote' },
  { q: 'Holy forking shirtballs.', who: 'Eleanor Shellstrop', show: 'The Good Place', tags: ['surprise', 'profanity', 'censored', 'holy', 'forking', 'shirtballs'], episode: '3.11', episodeName: 'Chapter 37 - The Book of Dougs', source: 'https://en.wikiquote.org/wiki/The_Good_Place', provenance: 'wikiquote-verified' },
  { q: 'Ya basic.', who: 'Eleanor Shellstrop', show: 'The Good Place', tags: ['insult', 'dismissal', 'catchphrase', 'basic'], provenance: 'owner-confirmed' },
  { q: 'Somebody royally forked up.', who: 'Eleanor Shellstrop', show: 'The Good Place', tags: ['error', 'blame', 'censored', 'royally', 'forked'], episode: '1.1', episodeName: 'Chapter 1 – Everything is Fine', source: 'https://en.wikiquote.org/wiki/The_Good_Place', provenance: 'wikiquote-verified' },
  { q: 'I will not. It is literally impossible for me to do that.', who: 'Janet', show: 'The Good Place', tags: ['impossible'], episode: '1.13', episodeName: 'Chapter 13 – Michael\'s Gambit', source: 'https://en.wikiquote.org/wiki/The_Good_Place', provenance: 'wikiquote' },
  { q: 'I don\'t have a house, Jason. I live in a boundless void.', who: 'Janet', show: 'The Good Place', tags: ['house', 'live', 'boundless', 'void'], episodeName: 'Chapter 14 & 15 – Everything is Great! [2.1-2]', source: 'https://en.wikiquote.org/wiki/The_Good_Place', provenance: 'wikiquote' },
  { q: 'Fun fact: mathematically, it\'s equally likely to either im- or explode.', who: 'Janet', show: 'The Good Place', tags: ['fact', 'mathematically', 'equally', 'likely', 'either', 'explode'], episode: '2.7', episodeName: 'Chapter 20 – Janet and Michael', source: 'https://en.wikiquote.org/wiki/The_Good_Place', provenance: 'wikiquote' },
  { q: 'I came up with hundreds of plans in my life, and only one of them got me killed.', who: 'Jason Mendoza', show: 'The Good Place', tags: ['hundreds', 'plans', 'life', 'killed'], episode: '1.4', episodeName: 'Chapter 4 – Jason Mendoza', source: 'https://en.wikiquote.org/wiki/The_Good_Place', provenance: 'wikiquote' },
  { q: 'I\'m too young to die and too old to eat off the kids\' menu. What a stupid age I am.', who: 'Jason Mendoza', show: 'The Good Place', tags: ['death', 'mortality', 'dark', 'food', 'hunger', 'eating', 'intelligence', 'insult', 'young', 'kids'], episode: '2.3', episodeName: 'Chapter 16 – Dance Dance Resolution', source: 'https://en.wikiquote.org/wiki/The_Good_Place', provenance: 'wikiquote' },
  { q: 'Bortles!', who: 'Jason Mendoza', show: 'The Good Place', tags: ['catchphrase', 'football', 'enthusiasm', 'bortles'], provenance: 'owner-confirmed' },
  { q: 'For a being like me, retirement is not something fun.', who: 'Michael', show: 'The Good Place', tags: ['retirement'], episode: '1.7', episodeName: 'Chapter 7 – The Eternal Shriek', source: 'https://en.wikiquote.org/wiki/The_Good_Place', provenance: 'wikiquote' },
  { q: 'As long as I\'m with you guys, I\'m always in the fake Good Place.', who: 'Michael', show: 'The Good Place', tags: ['time', 'long', 'fake', 'good', 'place'], episode: '2.10', episodeName: 'Chapter 23 – Best Self', source: 'https://en.wikiquote.org/wiki/The_Good_Place', provenance: 'wikiquote' },
  { q: 'Take it sleazy.', who: 'Michael', show: 'The Good Place', tags: ['farewell', 'goodbye', 'send-off', 'sleazy'], episode: '1.7', episodeName: 'Chapter 7 – The Eternal Shriek', source: 'https://en.wikiquote.org/wiki/The_Good_Place', provenance: 'wikiquote-verified' },
  { q: 'I would say I outdid myself, but I\'m always this good. So I simply did myself.', who: 'Tahani Al-Jamil', show: 'The Good Place', tags: ['time', 'outdid', 'good', 'simply'], episode: '2.5', episodeName: 'Chapter 18 – Existential Crisis', source: 'https://en.wikiquote.org/wiki/The_Good_Place', provenance: 'wikiquote' },
  { q: 'You know, Jason, every single detail about your life is deeply disturbing. And yet, I envy you. I was never allowed to goof off.', who: 'Tahani Al-Jamil', show: 'The Good Place', tags: ['time', 'confusion', 'understanding', 'single', 'detail', 'life', 'deeply'], episode: '2.8', episodeName: 'Chapter 21 – Derek', source: 'https://en.wikiquote.org/wiki/The_Good_Place', provenance: 'wikiquote' },
  { q: 'Don\'t be so bloody ridiculous. Judges aren\'t food, judges are serious people who wear long, silk nightgowns and big, white powdered wigs.', who: 'Tahani Al-Jamil', show: 'The Good Place', tags: ['food', 'hunger', 'eating', 'bloody', 'ridiculous', 'judges', 'serious'], episode: '2.12', episodeName: 'Chapter 25 – The Burrito', source: 'https://en.wikiquote.org/wiki/The_Good_Place', provenance: 'wikiquote' },
  { q: 'Welcome! Everything is fine.', who: 'The Good Place', show: 'The Good Place', tags: ['reassurance', 'ominous', 'signage', 'welcome', 'fine'], source: 'https://en.wikiquote.org/wiki/The_Good_Place', provenance: 'wikiquote-verified' },
  { q: 'My heart belongs to music. But my ass belongs to these people.', who: 'Andy Bernard', show: 'The Office', tags: ['heart', 'belongs', 'music'], episode: '8.2', episodeName: 'The Incentive', source: 'https://en.wikiquote.org/wiki/The_Office_%28season_8%29', provenance: 'wikiquote' },
  { q: 'Hazing is a fun way to show a new employee that she is not welcome or liked.', who: 'Dwight Schrute', show: 'The Office', tags: ['work', 'job', 'career', 'television', 'film', 'media', 'hazing', 'show', 'employee', 'welcome'], episode: '4.18 & 4.19', episodeName: 'Goodbye, Toby', source: 'https://en.wikiquote.org/wiki/The_Office_%28season_4%29', provenance: 'wikiquote' },
  { q: 'BUTTLICKER, OUR PRICES HAVE NEVER BEEN LOWER!', who: 'Dwight Schrute', show: 'The Office', tags: ['time', 'buttlicker', 'prices', 'lower'], episode: '5.07', episodeName: 'Customer Survey', source: 'https://en.wikiquote.org/wiki/The_Office_%28season_5%29', provenance: 'wikiquote' },
  { q: 'I always knew I would be destroyed by my own creation, but honestly I thought it would be that bull that Mose and I are trying to reanimate.', who: 'Dwight Schrute', show: 'The Office', tags: ['time', 'confusion', 'understanding', 'destroyed', 'creation', 'honestly', 'bull'], episode: '6.23', episodeName: 'Body Language', source: 'https://en.wikiquote.org/wiki/The_Office_%28season_6%29', provenance: 'wikiquote' },
  { q: 'Most people don\'t even know that a candy cane represents a shepherd\'s crook. Which I assure you does not taste like peppermint. It tastes like sheep feces.', who: 'Dwight Schrute', show: 'The Office', tags: ['food', 'hunger', 'eating', 'confusion', 'understanding', 'even', 'candy', 'cane', 'represents'], episode: '9.9', episodeName: 'Dwight Christmas', source: 'https://en.wikiquote.org/wiki/The_Office_%28season_9%29', provenance: 'wikiquote' },
  { q: 'Whenever I\'m about to do something, I think, "Would an idiot do that?" And if they would, I do not do that thing.', who: 'Dwight Schrute', show: 'The Office', tags: ['intelligence', 'insult', 'whenever', 'idiot'], episode: '3.17', episodeName: 'Business School', source: 'https://en.wikiquote.org/wiki/The_Office_%28season_3%29', provenance: 'wikiquote' },
  { q: 'Second Life is not a game. It is a multi-user, virtual environment. It doesn\'t have points or scores. It doesn\'t have winners or losers.', who: 'Dwight Schrute', show: 'The Office', tags: ['technology', 'internet', 'life', 'game', 'multi', 'user', 'virtual'], episode: '4.09', episodeName: 'Local Ad', source: 'https://en.wikiquote.org/wiki/The_Office_%28season_4%29', provenance: 'wikiquote' },
  { q: 'Whoa. That butoxide has a mild hallucinogenic effect, but I don\'t think it\'s kicked in yet. I\'m gonna count down from ten. Ten, nine, yellow, cold, sad, purple...', who: 'Dwight Schrute', show: 'The Office', tags: ['sad', 'crying', 'emotion', 'whoa', 'butoxide', 'mild', 'hallucinogenic', 'effect'], episode: '9.10', episodeName: 'Lice', source: 'https://en.wikiquote.org/wiki/The_Office_%28season_9%29', provenance: 'wikiquote' },
  { q: 'Identity theft is not a joke, Jim! Millions of families suffer every year.', who: 'Dwight Schrute', show: 'The Office', tags: ['outrage', 'warning', 'serious', 'time', 'identity', 'theft', 'joke', 'millions', 'families', 'suffer'], episode: '3.21', episodeName: 'Product Recall', source: 'https://en.wikiquote.org/wiki/The_Office_%28season_3%29', provenance: 'wikiquote-verified' },
  { q: 'Five minutes actually. I am a black belt in gift wrapping.', who: 'Jim Halpert', show: 'The Office', tags: ['five', 'minutes', 'black', 'belt', 'gift'], episode: '5.11', episodeName: 'Moroccan Christmas', source: 'https://en.wikiquote.org/wiki/The_Office_%28season_5%29', provenance: 'wikiquote' },
  { q: 'Bears. Beets. Battlestar Galactica.', who: 'Jim Halpert (as Dwight)', show: 'The Office', tags: ['impression', 'list', 'nonsense', 'bears', 'beets', 'battlestar', 'galactica'], episode: '3.21', episodeName: 'Product Recall', source: 'https://en.wikiquote.org/wiki/The_Office_%28season_3%29', provenance: 'wikiquote-verified' },
  { q: 'Fact. Bears eat beets.', who: 'Jim Halpert (as Dwight)', show: 'The Office', tags: ['impression', 'fact', 'absurd', 'food', 'hunger', 'eating', 'bears', 'beets'], episode: '3.21', episodeName: 'Product Recall', source: 'https://en.wikiquote.org/wiki/The_Office_%28season_3%29', provenance: 'wikiquote-verified' },
  { q: 'I swore to myself that if I ever got to walk around the room as manager, people would laugh when they saw me coming and would applaud as I walked away.', who: 'Michael Scott', show: 'The Office', tags: ['work', 'job', 'career', 'swore', 'ever', 'walk', 'around', 'room'], episode: '2.14', episodeName: 'The Carpet', source: 'https://en.wikiquote.org/wiki/The_Office_%28season_2%29', provenance: 'wikiquote' },
  { q: 'I don\'t want somebody sucking up to me because they think I am going to help their career. I want them sucking up to me because they genuinely love me.', who: 'Michael Scott', show: 'The Office', tags: ['love', 'affection', 'romance', 'work', 'job', 'career', 'help', 'advice', 'sucking'], episode: '3.14', episodeName: 'The Return', source: 'https://en.wikiquote.org/wiki/The_Office_%28season_3%29', provenance: 'wikiquote' },
  { q: 'I\'m not superstitious, but I...I am a little stitious.', who: 'Michael Scott', show: 'The Office', tags: ['superstitious', 'stitious'], episode: '4.01 & 4.02', episodeName: 'Fun Run', source: 'https://en.wikiquote.org/wiki/The_Office_%28season_4%29', provenance: 'wikiquote' },
  { q: 'Would I rather be feared or loved? Umm... easy, both. I want people to be afraid of how much they love me.', who: 'Michael Scott', show: 'The Office', tags: ['love', 'affection', 'romance', 'fear', 'rather', 'feared', 'loved', 'easy', 'afraid'], episode: '2.06', episodeName: 'The Fight', source: 'https://en.wikiquote.org/wiki/The_Office_%28season_2%29', provenance: 'wikiquote' },
  { q: 'You know what, I resent the implication that I would keep that secret. Everyone here knows that I can\'t and won\'t keep a secret.', who: 'Michael Scott', show: 'The Office', tags: ['honesty', 'lying', 'secrets', 'anger', 'contempt', 'confusion', 'understanding', 'resent', 'implication'], episode: '6.22', episodeName: 'Secretary\'s Day', source: 'https://en.wikiquote.org/wiki/The_Office_%28season_6%29', provenance: 'wikiquote' },
  { q: 'Toby is in HR, which technically means he works for corporate, so he\'s not really a part of our family. Also, he\'s divorced, so he\'s really not a part of his family.', who: 'Michael Scott', show: 'The Office', tags: ['toby', 'technically', 'means', 'works', 'corporate', 'he\'s'], episode: '2.02', episodeName: 'Sexual Harassment', source: 'https://en.wikiquote.org/wiki/The_Office_%28season_2%29', provenance: 'wikiquote' },
  { q: 'That\'s what she said.', who: 'Michael Scott', show: 'The Office', tags: ['innuendo', 'rejoinder', 'joke'], source: 'https://en.wikiquote.org/wiki/The_Office_%28season_2%29', provenance: 'wikiquote-verified' },
  { q: 'I am Beyoncé, always.', who: 'Michael Scott', show: 'The Office', tags: ['confidence', 'ego', 'identity', 'time', 'beyonc'], provenance: 'owner-confirmed' },
  { q: 'I DECLARE BANKRUPTCY!', who: 'Michael Scott', show: 'The Office', tags: ['money', 'debt', 'declaration', 'failure', 'declare', 'bankruptcy'], episode: '4.07 & 4.08', episodeName: 'Money', source: 'https://en.wikiquote.org/wiki/The_Office_%28season_4%29', provenance: 'wikiquote-verified' },
  { q: 'Sometimes I\'ll start a sentence and I don\'t even know where it\'s going. I just hope I find it along the way.', who: 'Michael Scott', show: 'The Office', tags: ['confusion', 'rambling', 'lost', 'improvise', 'understanding', 'sometimes', 'start', 'sentence', 'even', 'hope'], episode: '5.12', episodeName: 'The Duel', source: 'https://en.wikiquote.org/wiki/The_Office_%28season_5%29', provenance: 'wikiquote-verified' },
  { q: 'The worst thing about prison was the Dementors.', who: 'Michael Scott (as Prison Mike)', show: 'The Office', tags: ['prison', 'fear', 'mixup', 'mistake', 'failure', 'regret', 'crime', 'law', 'worst'], provenance: 'owner-confirmed' },
  { q: 'I can\'t be around sad people, it just makes me sad.', who: 'Phyllis Vance', show: 'The Office', tags: ['sad', 'crying', 'emotion', 'around', 'makes'], episode: '9.16', episodeName: 'Moving On', source: 'https://en.wikiquote.org/wiki/The_Office_%28season_9%29', provenance: 'wikiquote' },
  { q: 'This is not the meal I was promised. I\'m going to have no energy for the rest of the day.', who: 'Stanley Hudson', show: 'The Office', tags: ['food', 'hunger', 'eating', 'time', 'meal', 'promised', 'energy', 'rest'], episode: '7.07', episodeName: 'Christening', source: 'https://en.wikiquote.org/wiki/The_Office_%28season_7%29', provenance: 'wikiquote' },
  { q: 'I don\'t know how I\'m going to get through this. I don\'t want to lie and I DON\'T want to tell the truth.', who: 'Toby Flenderson', show: 'The Office', tags: ['honesty', 'lying', 'secrets', 'confusion', 'understanding', 'truth'], episode: '6.14', episodeName: 'The Banker', source: 'https://en.wikiquote.org/wiki/The_Office_%28season_6%29', provenance: 'wikiquote' },
];

/** Every quote text, normalised, for validating model output against the bank. */
export const QUOTE_TEXTS: ReadonlySet<string> = new Set(
  QUOTES.map((x) => x.q.toLowerCase().replace(/[^a-z0-9 ]/g, ' ').replace(/\s+/g, ' ').trim()),
);
