// Generated by quotes-review/gen_client.py. Do not hand-edit.
//
// The Worker validates model output against the full bank, but these lines
// run in the browser when the Worker is unreachable — so nothing server-side
// can vouch for them. Generating them from the same source data is what keeps
// them honest. `npm test` asserts every one still exists in the bank.

export interface BankedQuote {
  q: string;
  who: string;
  show: string;
}

export const FALLBACK_QUOTES: BankedQuote[] = [
  { q: 'I don\'t want to sound like a defeatist, but...we\'re defeated.', who: 'Jeff Winger', show: 'Community' },
  { q: 'I don\'t understand the question, and I won\'t respond to it.', who: 'Lucille Bluth', show: 'Arrested Development' },
  { q: 'I will not. It is literally impossible for me to do that.', who: 'Janet', show: 'The Good Place' },
  { q: 'I don\'t know what I expected.', who: 'Michael Bluth', show: 'Arrested Development' },
];

export const GREETING_QUOTES: BankedQuote[] = [
  { q: 'Ann, you beautiful tropical fish.', who: 'Leslie Knope', show: 'Parks and Recreation' },
];
