"""Generate the small client-side quote subset.

The full bank lives in the Worker. The browser only needs the handful used by
offline fallbacks, so shipping all 129 would add ~50KB to the bundle for a path
that only runs when the network is already broken. This emits just those, from
the same source data, so they are provably banked.
"""
import json

PICKS = {
  'FALLBACK': ["I don't want to sound like a defeatist",
               "I don't understand the question",
               'It is literally impossible for me',
               "I don't know what I expected"],
  'GREETING': ['you beautiful tropical fish'],
}
rows = json.load(open('candidates.json'))
def find(frag):
    for r in rows:
        if frag.lower() in r['q'].lower(): return r
    raise SystemExit(f'not in bank: {frag}')

def esc(s): return s.replace('\\','\\\\').replace("'","\\'")
L=["// Generated by quotes-review/gen_client.py. Do not hand-edit.",
"//",
"// The Worker validates model output against the full bank, but these lines",
"// run in the browser when the Worker is unreachable — so nothing server-side",
"// can vouch for them. Generating them from the same source data is what keeps",
"// them honest. `npm test` asserts every one still exists in the bank.",
"",
"export interface BankedQuote {",
"  q: string;",
"  who: string;",
"  show: string;",
"}",""]
for name, frags in PICKS.items():
    L.append(f"export const {name}_QUOTES: BankedQuote[] = [")
    for f in frags:
        r = find(f)
        L.append(f"  {{ q: '{esc(r['q'])}', who: '{esc(r['who'])}', show: '{esc(r['show'])}' }},")
    L += ["];",""]
open('../src/commands/banked-quotes.ts','w').write('\n'.join(L))
print('wrote src/commands/banked-quotes.ts')
